apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-insights-api
  labels:
    app: stock-insights-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-insights-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: stock-insights-api
    spec:
      containers:
      - name: api
        image: IMAGE_TO_REPLACE
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: DB_HOST
          value: "cockroachdb"
        - name: DB_PORT
          value: "26257"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: ""
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: dbname
        - name: DB_SSL_MODE
          value: "disable"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
      restartPolicy: Always