apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/stock-insights-457603/docker-images/golang-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "cockroachdb-0"
        - name: DB_PORT
          value: "26257"
        - name: DB_USER
          value: "root"
        - name: DB_SSL_MODE
          value: "disable"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer