apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "backend-certificate"
    cloud.google.com/backend-config: '{"default": "backend-config"}'
spec:
  rules:
  - host: api.soyrobert.co
    http:
      paths:
      - path: /health
        pathType: Exact
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80