apiVersion: v1
kind: Service
metadata:
  name: stock-insights-api
  labels:
    app: stock-insights-api
spec:
  selector:
    app: stock-insights-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP