name: 'Deploy Backend'

on:
  push:
    branches: [ main, feat/* ]

jobs:
  build-and-deploy:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
        
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker
      
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/golang-backend:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/golang-backend:${{ github.sha }}
        
    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials backend-cluster --zone ${{ secrets.GCP_ZONE }}
        kubectl set image deployment/backend-app backend=gcr.io/${{ secrets.GCP_PROJECT_ID }}/golang-backend:${{ github.sha }}