name: 'Deploy Backend'

on:
  push:
    branches: [ main, feat/* ]

jobs:
  build-and-deploy:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
        
    - name: Install GKE Auth Plugin
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
        
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-images/golang-backend:${{ github.sha }} .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-images/golang-backend:${{ github.sha }}
        
    - name: Get Image Digest
      id: image
      run: |
        # Esperar un momento para asegurar que la imagen esté disponible en Artifact Registry
        sleep 5
        # Obtener el digest de la imagen recién subida
        DIGEST=$(gcloud artifacts docker images describe us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-images/golang-backend:${{ github.sha }} --format='value(image_summary.fully_qualified_digest)')
        echo "DIGEST=$DIGEST" >> $GITHUB_OUTPUT
        
    - name: Deploy to GKE
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials backend-cluster --zone ${{ secrets.GCP_ZONE }}
        
        # Reemplazar el placeholder en el archivo de deployment
        sed -i "s|PROJECT_ID_PLACEHOLDER|${{ secrets.GCP_PROJECT_ID }}|g" kubernetes/deployment.yaml
        
        # Actualizar la imagen en el archivo de deployment antes de aplicarlo
        sed -i "s|us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-images/golang-backend:.*|${{ steps.image.outputs.DIGEST }}|g" kubernetes/deployment.yaml
        
        # Intentar obtener el deployment para verificar si existe
        if kubectl get deployment backend-app &> /dev/null; then
          # Si existe, actualizar la imagen usando el digest
          kubectl set image deployment/backend-app backend=${{ steps.image.outputs.DIGEST }}
        else
          # Si no existe, aplicar el archivo de configuración actualizado
          kubectl apply -f kubernetes/deployment.yaml
        fi